blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/4ngel2769/minecraft-server-status/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/4ngel2769/minecraft-server-status#readme
    about: Read the documentation and guides
